spring.application.name=Torque

# Master MySQL Configuration
spring.datasource.master.url=jdbc:mysql://localhost:3307/torque_master?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.master.username=root
spring.datasource.master.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Security Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access token expiry: 15 minutes (in milliseconds)
application.security.jwt.expiration=900000
# Refresh token expiry: 7 days (in milliseconds)
application.security.jwt.refresh-token.expiration=604800000

sms.textlk.api-token=4909|Z3wn4fzOXtBYBlGXgpIfyW72k0hzPvLtIss9HMSta38b38cb
sms.textlk.sender-id=TextLKDemo
sms.enabled=true
